package blog

import scala.collection.mutable.ListBuffer

object ListOperations {


  def main(args:Array[String]):Unit ={

    val mutableList: ListBuffer[Int] = ListBuffer(0)   // ListBuffer is by default mutable no matter val or var used

    val duplicate:List[String] = List("abc","abc","xyz","pqr","xyz","mn","fff","mn")

    val num: List[Int] = List(1, 2, 3, 4, 5)          // List is by default immutable no matter val or var used

    val fruits:List[String] = List("Apple","Mango","Banana","Strawberry","Peas")

    // head : Returns the first element of this iterable collection
    println(num.head)
    println(fruits.head)

    // headOption : Returns the first element of this iterable collection if it is nonempty, None if it is empty.
    // Better to use headOption since it return an option and handles null
    println(num.headOption)
    println(fruits.headOption)

    //tail: The rest of the collection without its first element.
    println(num.tail)

    // isEmpty: if list is empty returns true else false
    println(num.isEmpty)

    // map() : transforms a list by applying a function to every individual element and returning a new list with the modified results.
    println("The doubled list using map is:"+" "+num.map(x=>x*2))

    // contains : Tests whether this sequence contains a given value as an element and returns boolean .
    println(num.contains(3))

    //exists() : checks whether at least one element in the list meets a specific condition
    println(".exists() output"+num.exists(x=>x%2 ==0))

    // appendAll : adds all the elements of another collection to the end of a mutable collection.
    println("Only works on mutable list :"+" "+mutableList.appendAll(num))

    // appendedAll : It returns a new immutable list combining both collections, leaving the original list completely unchanged.
    println("Works on immutable list and encouraged to use :"+" "+fruits.appendedAll(num))

    // filter: creates a new immutable list containing only the elements that match the specified condition.
    println(num.filter(x=>x%2!=0))

    //find: searches a list from left to right and returns the very first element that matches the condition, wrapped in an Option
    println(num.find(x=>x>3))

    //flatMap: transforms each element into a new collection and then flattens all the resulting collections into a single, combined list.
    println(fruits.flatMap(x=>x.toList))


    /* fold: combines all elements of a list into a single value by applying a binary operation,
     starting with a baseline value called a z-value (or initial value).*/
    // 0 is the initial z-value. (acc, num) represents (accumulator, current_number)
    val totalSum = num.fold(0)((acc, num) => acc + num)
    println("Total sum of num list:"+" "+totalSum)


    // foreach: Executes an action on every element for its side-effects, returning absolutely nothing.
    val newList:Unit =num.foreach(x=>println(x+2))

    //forall: Checks whether every single element in the list satisfies a specific condition.
    println(num.forall(x=>x>0))

    // reverse : Returns a new sequence with all elements of this sequence in reverse order.
    println(num.reverse)

    // groupBy: splits a list into a Map of sub-lists, grouping the elements together based on a key generated by a function provided
    println(num.groupBy(x=>x%2==0))

    //distinct: Automatically strips out duplicate elements from a collection
    println("Removed duplicate items from the list:"+" "+duplicate.distinct)

    // mkString: Turns a list into a cleanly formatted string with separators
    println("Converted num list to string:"+" "+num.mkString(" "))

    // sortBy: Sorts the elements of a list in ascending order based on an attribute or transformation function provided
    println("Sorted the fruits list based on fruits string length:"+" "+fruits.sortBy(fruit=>fruit.length))



    // sortWith: sorts a list by using a custom comparison function that compares two elements at a time.
    println("Decending:"+num.sortWith((a,b)=>a>b))


    // take: Extracts the first n elements.
    println("First 3 element of list duplicate:" +duplicate.take(3))

    // drop: Skips the first n elements
    println("Elements after first 3 elements of duplicate:"+ duplicate.drop(3))

    // Prepending is O(1), appending is O(n)
    val fastList = 0 :: num // Standard way to prepend (same as 0 +: num)
    println(s"Prepended using cons: $fastList")

    // Creating a List (The Construction Hat) --> :: this operator strictly belong to list only
    /* When we use :: between normal variables,
     it behaves just like +:. It takes an element on the left and attaches it to a list on the right.*/
    val headEg = 1
    val tailEg = List(2, 3, 4)

    val newListEg = headEg :: tailEg // Result: List(1, 2, 3, 4)
    println("New list created with :: -> "+ newListEg)

    // Pattern Matching (The Deconstruction Hat)
    /* When we use :: inside a case statement, we aren't combining anything.
     We are doing the exact opposite: we are splitting an existing list apart. */
    // If your list is List(1, 2, 3, 4)
    num match {
      case head :: tail => // Scala extracts: head = 1, tail = List(2, 3, 4)
        println(s"The extracted head is: $head")        // Output: 1
        println(s"The extracted tail is: $tail")        // Output: List(2, 3, 4)

      // This case only runs if the list is completely empty
      case Nil =>
        println("The list was empty, nothing to split!")
    }
    /* The Performance Trap (+: vs :+): Appending to the front of a List (+:) is $O(1)$ (instantaneous) because it just links a new head.
     Appending to the back (:+) is $O(n)$ (slow) because Scala has to copy the entire list to reach the end. If you need to append to the
     back constantly, use Vector instead.
     The Cons Operator (::): This is the quintessential idiomatic Scala way to build or prepend to a list.  */


    
  }
}
